os: osx
osx_image: xcode10.1
language: swift
before_install:
- pod repo update > /dev/null
script:
- set -o pipefail
- xcodebuild test -workspace Vox.xcworkspace -scheme Vox -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0' ONLY_ACTIVE_ARCH=NO
- pod lib lint
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'Vox'